const imageBase = 'clientes/kechicharron/';
const products = [
  { id: 'patacon', category: 'Favoritos', name: 'Patacón relleno', description: 'Pollo, cerdo, butifarra, mozzarella, maíz y salsas.', price: 20000, image: imageBase + 'patacon relleno .jpg' },
  { id: 'personal', category: 'Chicharrones', name: 'Chicharrón personal', description: 'Con yuca o patacones y suero.', price: 17000, image: imageBase + 'chicharron de 17mil.jpg' },
  { id: 'doble', category: 'Chicharrones', name: 'Chicharrón doble', description: 'Una porción generosa para compartir.', price: 30000, image: imageBase + 'chicharron doble.jpg' },
  { id: 'chuletazo', category: 'Asados', name: 'Chuletazo', description: 'Acompañado con patacones y ensalada.', price: 20000, image: imageBase + 'chuletazo.jpg' },
  { id: 'pechuga', category: 'Asados', name: 'Pechuga gratinada', description: 'Con papas o patacones y ensalada.', price: 25000, image: imageBase + 'pechuga gratinada.jpg' },
  { id: 'mixto', category: 'Asados', name: 'Asado mixto', description: 'Pechuga, chuleta y carne con acompañamiento.', price: 30000, image: imageBase + 'asado mixto.jpg' }
];
const cart = [];
const money = value => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(value);
const menuGrid = document.getElementById('menu-grid');
function renderMenu(category = 'Todos') { menuGrid.innerHTML = products.filter(product => category === 'Todos' || product.category === category).map(product => `<article class="product-card"><div class="product-image" style="background-image:url('${encodeURI(product.image)}')"></div><div class="product-info"><span>${product.category}</span><h3>${product.name}</h3><p>${product.description}</p><div class="product-footer"><strong>${money(product.price)}</strong><button data-product="${product.id}" aria-label="Agregar ${product.name}">+</button></div></div></article>`).join(''); }
function renderCategories() { const categories = ['Todos', ...new Set(products.map(product => product.category))]; document.getElementById('categories').innerHTML = categories.map((category, index) => `<button class="category-button ${index === 0 ? 'active' : ''}" data-category="${category}">${category}</button>`).join(''); }
function renderCart() { const count = cart.reduce((total, item) => total + item.quantity, 0); document.getElementById('cart-count').textContent = count; document.getElementById('cart-items').innerHTML = cart.length ? cart.map(item => `<div class="cart-item"><div><strong>${item.name}</strong><small>${money(item.price)}</small></div><div class="quantity"><button data-decrease="${item.id}">−</button><b>${item.quantity}</b><button data-increase="${item.id}">+</button></div></div>`).join('') : '<p class="empty">Tu carrito está vacío. Agrega algo delicioso.</p>'; document.getElementById('cart-total').textContent = money(cart.reduce((total, item) => total + item.price * item.quantity, 0)); }
function showToast(message) { const toast = document.getElementById('toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2400); }
document.addEventListener('click', event => { const productButton = event.target.closest('[data-product]'); if (productButton) { const product = products.find(item => item.id === productButton.dataset.product); const item = cart.find(entry => entry.id === product.id); if (item) item.quantity += 1; else cart.push({ ...product, quantity: 1 }); renderCart(); showToast(`${product.name} agregado al pedido`); } const category = event.target.closest('[data-category]'); if (category) { document.querySelectorAll('.category-button').forEach(button => button.classList.remove('active')); category.classList.add('active'); renderMenu(category.dataset.category); } const increase = event.target.closest('[data-increase]'); if (increase) { cart.find(item => item.id === increase.dataset.increase).quantity += 1; renderCart(); } const decrease = event.target.closest('[data-decrease]'); if (decrease) { const item = cart.find(entry => entry.id === decrease.dataset.decrease); item.quantity -= 1; if (item.quantity <= 0) cart.splice(cart.indexOf(item), 1); renderCart(); } });
document.getElementById('open-cart').addEventListener('click', () => document.getElementById('cart-drawer').classList.add('open')); document.getElementById('close-cart').addEventListener('click', () => document.getElementById('cart-drawer').classList.remove('open')); document.getElementById('checkout').addEventListener('click', () => { if (!cart.length) return showToast('Agrega productos antes de confirmar'); const orderId = `POS-${Math.floor(1000 + Math.random() * 9000)}`; cart.length = 0; renderCart(); document.getElementById('cart-drawer').classList.remove('open'); showToast(`Pedido #${orderId} recibido. ¡Gracias!`); });
renderCategories(); renderMenu(); renderCart();